### ISSUE TITLE
Leyenda de color sale diferente en Safari

### ISSUE THREAD

**Issue by sbegueria** [lcsc/ncwebmapper#1]
En el navegador Safari sale la leyenda de color diferente (de blancos / amarillos a azules), tanto en ordenadores (macOS) como en dispositivos móviles (iOS).

En cambio, en Firefox sale la leyenda típica (rojos a azules).

**Comment by fergusreiggracia** [comment]
https://monitordesequia.csic.es/ y https://spei.csic.es/map/ me salen correctamente.
https://global-drought-crops.csic.es/, https://spei.csic.es/spei_database/, https://sedi.csic.es/, https://flash-drought.csic.es/ y https://semiarid-drought-monitor.csic.es/ me salen en una escala de azules. Parece ser un problema ligado a ncwebmapper.
