### ISSUE TITLE
Unir NCs Penisnsula y Canarias

### ISSUE THREAD

**Issue by danielvilas** [lcsc/ncwebmapper#20]

**Comment by eduardofilo** [comment]
Hecho mediante la función fusion_pen_can de ncartifactgenerator, aunque en desuso tras la modificación de ncartifactgenerator y VisorServiciosClimaticos para que soporten múltiples NCs:
https://github.com/lcsc/ncartifactgenerator/blob/master/R/chunk.R#L584
