### ISSUE TITLE
Cambiar Tiles por Lectura al Vuelo usando Open Layers

### ISSUE THREAD

**Issue by B0RJA** [lcsc/ncwebmapper#7]
Valorar usar, en lugar de tiles, la reproyección al vuelo de OpenLayers a partir de un netcdf donde cada chunk es un mapa y la parte JS que está haciendo @eduardofilo para la descargar con range requests

https://openlayers.org/en/latest/examples/reprojection-image.html

**Comment by eduardofilo** [comment]
Prueba de concepto desarrollada en repositorio [lcsc/proto_ol](https://github.com/lcsc/proto_ol).

Instalada en https://calculador11.ipe.csic.es/proto_ol/
