### ISSUE TITLE
Cambiar CSVs por Lectura al Vuelo

### ISSUE THREAD

**Issue by B0RJA** [lcsc/ncwebmapper#8]
# Lectura al vuelo de los NetCDF
Ahora mismo se estan generando un monton de CSV (uno por pixel del mapa), la libreria genera un NetCDF con los datos ordenados por pixel (todos los datos de un pixel continuo en el fichero) de tal forma que es posible procesar al vuelo. El proceso seria:
1. Pedir al apache la cabecera del fichero (Streaming Headers)
2. Leer la cabecera del NetCDF
4. Transformar XY -> coordenadas LatLong -> Indice de pixel
5. Buscar el punto de inicio y final del pixel, usando el indice
6. Pedir al apache solo el chunck del pixel
7. Descomprimir el chunk
8. Convertir el chunk a CSV u otro array que le sirva a dygraphs
9. Mostrar el grafico con la "funcion actual"

**Comment by eduardofilo** [comment]
Prueba de concepto desarrollada en repositorio [lcsc/proto_csv](https://github.com/lcsc/proto_csv).

Instalada en https://calculador11.ipe.csic.es/proto_csv/
